# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='divices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divice_ip', models.CharField(max_length=50, unique=True, verbose_name='ip地址')),
                ('divice_location', models.EmailField(max_length=50, verbose_name='站点名称')),
                ('divice_site', models.EmailField(max_length=50, verbose_name='MDC1')),
                ('divice_communication', models.CharField(max_length=50, verbose_name='协议类型')),
                ('divice_type', models.CharField(max_length=50, verbose_name='机器型号')),
                ('divice_serial', models.CharField(max_length=50, verbose_name='机器序列号')),
                ('user_id', models.ManyToManyField(to='rbac.User', verbose_name='站点关联的用户')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
                'db_table': 'tb_divices',
            },
        ),
    ]
