# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cameras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_site', models.CharField(max_length=20, null=True, verbose_name='MDC1')),
                ('cam_location', models.CharField(max_length=20, null=True, verbose_name='站点位置')),
                ('cam_address', models.CharField(max_length=20, verbose_name='摄像头IP')),
                ('cam_ip', models.CharField(max_length=20, verbose_name='站点IP')),
                ('cam_other', models.CharField(max_length=20, null=True, verbose_name='其他')),
            ],
            options={
                'verbose_name': '站点摄像头配置',
                'verbose_name_plural': '站点摄像头配置',
                'db_table': 'tb_Cameras',
            },
        ),
        migrations.CreateModel(
            name='coordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_ip', models.CharField(max_length=50, unique=True, verbose_name='ip地址')),
                ('coordinate_location', models.CharField(max_length=50, null=True, verbose_name='站点名称')),
                ('coordinate_site', models.CharField(max_length=50, null=True, verbose_name='MDC1')),
                ('coordinate_status', models.CharField(max_length=50, null=True, verbose_name='告警状态')),
                ('coordinate_A', models.FloatField(max_length=30, verbose_name='坐标点A')),
                ('coordinate_B', models.FloatField(max_length=30, verbose_name='坐标点B')),
                ('coordinate_address', models.CharField(max_length=150, null=True)),
            ],
            options={
                'verbose_name': '坐标点',
                'verbose_name_plural': '坐标点',
                'db_table': 'tb_coordinate',
            },
        ),
        migrations.CreateModel(
            name='divices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divice_ip', models.CharField(max_length=50, unique=True, verbose_name='ip地址')),
                ('divice_location', models.EmailField(max_length=50, null=True, verbose_name='站点名称')),
                ('divice_site', models.EmailField(max_length=50, null=True, verbose_name='MDC1')),
                ('divice_communication', models.CharField(max_length=50, null=True, verbose_name='协议类型')),
                ('divice_type', models.CharField(max_length=50, null=True, verbose_name='机器型号')),
                ('divice_serial', models.CharField(max_length=50, null=True, verbose_name='机器序列号')),
            ],
            options={
                'verbose_name': '站点信息',
                'verbose_name_plural': '站点信息',
                'db_table': 'tb_divices',
            },
        ),
        migrations.CreateModel(
            name='WarningConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_server', models.CharField(max_length=20, verbose_name='告警服务器')),
                ('con_port', models.CharField(max_length=20, verbose_name='告警站点端口')),
                ('con_method', models.CharField(max_length=20, verbose_name='告警站点端口')),
                ('con_account', models.EmailField(default='null', max_length=50)),
                ('con_password', models.CharField(max_length=20)),
                ('con_phone', models.CharField(max_length=20, verbose_name='站点电话')),
                ('con_ip', models.CharField(max_length=20, verbose_name='站点IP')),
                ('con_other', models.CharField(max_length=20, verbose_name='其他')),
            ],
            options={
                'verbose_name': '站点告警配置',
                'verbose_name_plural': '站点告警配置',
                'db_table': 'tb_warningconfig',
            },
        ),
    ]
