# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 01:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='divices',
            name='user_id',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='站点关联的用户'),
        ),
    ]
