# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_level', models.CharField(max_length=20, verbose_name='告警等级')),
                ('warn_text', models.CharField(max_length=20, verbose_name='告警内容')),
                ('warn_time', models.CharField(max_length=20, verbose_name='告警时间')),
                ('warn_name', models.CharField(max_length=20, verbose_name='告警设备')),
                ('warn_data', models.FloatField(default=None, max_length=20, verbose_name='数据信息值')),
                ('warn_ip', models.CharField(max_length=50, verbose_name='站点ip')),
                ('warn_other', models.CharField(max_length=20, verbose_name='其他')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('equip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='告警站点IP')),
            ],
            options={
                'verbose_name': '告警信息',
                'verbose_name_plural': '告警信息',
                'db_table': 'tb_warning',
            },
        ),
        migrations.CreateModel(
            name='WarningConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('con_address', models.CharField(max_length=20, verbose_name='告警站点地址')),
                ('con_port', models.CharField(max_length=20, verbose_name='告警站点端口')),
                ('con_email', models.EmailField(max_length=20, verbose_name='告警站点邮箱')),
                ('con_password', models.CharField(max_length=20, verbose_name='站点邮箱密码')),
                ('con_phone', models.CharField(max_length=20, verbose_name='站点电话')),
                ('con_ip', models.CharField(max_length=20, verbose_name='站点IP')),
                ('con_other', models.CharField(max_length=20, verbose_name='其他')),
                ('divice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip')),
            ],
            options={
                'verbose_name': '站点告警配置',
                'verbose_name_plural': '站点告警配置',
                'db_table': 'tb_warningconfig',
            },
        ),
    ]
