# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=25, verbose_name='EquipTemplateId')),
                ('site', models.CharField(max_length=25, verbose_name='告警的站点')),
                ('alarm', models.CharField(max_length=150, verbose_name='告警的名称')),
                ('alarm_text', models.CharField(max_length=50, verbose_name='告警的内容')),
                ('equipment', models.CharField(max_length=25, verbose_name='告警的设备')),
                ('level', models.CharField(max_length=25, verbose_name='告警等级')),
                ('manage', models.CharField(max_length=25, verbose_name='点关联的用户')),
                ('lssue_time', models.CharField(max_length=25, verbose_name='告警时间')),
                ('alarm_id', models.CharField(max_length=25, verbose_name='告警的ID')),
                ('alarm_ip', models.CharField(max_length=25, verbose_name='告警的IP')),
                ('alarm_flag', models.CharField(default='-', max_length=25, verbose_name='告警标识')),
            ],
            options={
                'verbose_name': '实时告警列表',
                'verbose_name_plural': '实时告警列表',
                'db_table': 'tb_AlarmContent',
            },
        ),
        migrations.CreateModel(
            name='HistoryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_site', models.CharField(max_length=20, verbose_name='站点')),
                ('equipment_equipment', models.CharField(max_length=20, verbose_name='设备')),
                ('equipment_parameter', models.CharField(max_length=20, verbose_name='参数')),
                ('equipment_value', models.CharField(max_length=20, verbose_name='值')),
                ('equipment_unit', models.CharField(default='-', max_length=20, verbose_name='单位')),
                ('equipment_time', models.CharField(max_length=20, verbose_name='时间')),
                ('equipment_ip', models.CharField(max_length=50, verbose_name='站点ip')),
                ('equipment_other', models.CharField(max_length=50, verbose_name='其他')),
            ],
            options={
                'verbose_name': '设备详细信息',
                'verbose_name_plural': '设备详细信息',
                'db_table': 'tb_historydata',
            },
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warn_site', models.CharField(max_length=20, verbose_name='告警站点')),
                ('warn_equipment', models.CharField(max_length=20, verbose_name='告警设备')),
                ('warn_parameter', models.CharField(max_length=20, verbose_name='告警参数')),
                ('warn_alarm', models.CharField(max_length=120, verbose_name='告警内容')),
                ('warn_value', models.CharField(max_length=20, verbose_name='告警值')),
                ('warn_unit', models.CharField(default='-', max_length=10, verbose_name='告警单位')),
                ('warn_level', models.CharField(max_length=20, verbose_name='告警等级')),
                ('warn_time', models.CharField(max_length=20, verbose_name='告警时间')),
                ('warn_ip', models.CharField(max_length=50, verbose_name='站点ip')),
                ('warn_other', models.CharField(max_length=20, verbose_name='其他')),
            ],
            options={
                'verbose_name': '告警信息',
                'verbose_name_plural': '告警信息',
                'db_table': 'tb_warning',
            },
        ),
    ]
