# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='warn_ip',
            field=models.CharField(max_length=50, verbose_name='站点ip'),
        ),
        migrations.AlterField(
            model_name='warning',
            name='warn_other',
            field=models.CharField(max_length=20, verbose_name='其他'),
        ),
    ]
