# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historydata',
            name='equipment_equipment',
            field=models.CharField(max_length=20, verbose_name='温湿度'),
        ),
        migrations.AlterField(
            model_name='historydata',
            name='equipment_site',
            field=models.CharField(max_length=20, verbose_name='MDC'),
        ),
    ]
