# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-16 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('divices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=50, verbose_name='服务器地址')),
                ('port_config', models.IntegerField(default=False, verbose_name='端口配置')),
                ('send_mail', models.CharField(max_length=50, verbose_name='发件箱')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('COM_phone', models.CharField(max_length=50, verbose_name='电话端口号')),
                ('other_config', models.CharField(max_length=50, verbose_name='其他设置')),
                ('divice_ip', models.CharField(default=False, max_length=50, verbose_name='关联ip字段')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
                'db_table': 'tb_addressconfig',
            },
        ),
        migrations.CreateModel(
            name='EqModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.IntegerField(default=0, verbose_name='模块ID')),
                ('model_name', models.CharField(max_length=20, verbose_name='模块名称')),
                ('model_data', models.CharField(max_length=50, verbose_name='模块内容')),
                ('model_class', models.CharField(max_length=20, verbose_name='模块分类')),
                ('model_ip', models.CharField(max_length=50, verbose_name='ip字段')),
                ('model_other', models.CharField(max_length=50, verbose_name='其他')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('equip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '环境模块',
                'verbose_name_plural': '环境模块',
                'db_table': 'tb_eqmodel',
            },
        ),
        migrations.CreateModel(
            name='EquipmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=50, verbose_name='设备')),
                ('equipment_name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('equipment_text', models.CharField(max_length=50, verbose_name='内容信息')),
                ('equipment_unit', models.CharField(max_length=20, verbose_name='单位')),
                ('equipment_folat', models.FloatField(default=False, verbose_name='信息值')),
                ('equipment_time', models.CharField(default=False, max_length=50, verbose_name='时间')),
                ('equipment_other', models.CharField(max_length=50, verbose_name='其他')),
                ('equipment_ip', models.CharField(max_length=50, verbose_name='ip字段')),
                ('divices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联IP')),
            ],
            options={
                'verbose_name': '设备详细信息',
                'verbose_name_plural': '设备详细信息',
                'db_table': 'tb_EquipmentData',
            },
        ),
    ]
