# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-08 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('createdata', '0001_initial'),
        ('divices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdata',
            name='divices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联IP'),
        ),
        migrations.AddField(
            model_name='eqmodel',
            name='equip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联设备'),
        ),
    ]
