# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-11 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divices', '0002_divices_user_id'),
        ('createdata', '0003_auto_20190710_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(max_length=50, verbose_name='服务器地址')),
                ('port_config', models.IntegerField(default=False, verbose_name='端口配置')),
                ('send_mail', models.CharField(max_length=50, verbose_name='发件箱')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('COM_phone', models.CharField(max_length=50, verbose_name='电话端口号')),
                ('other_config', models.CharField(max_length=50, verbose_name='其他设置')),
                ('divices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联站点')),
            ],
            options={
                'verbose_name_plural': '站点配置',
                'db_table': 'tb_addressconfig',
                'verbose_name': '站点配置',
            },
        ),
    ]
