# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-11 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0005_auto_20190711_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressconfig',
            name='divice_ip',
            field=models.CharField(default=False, max_length=50, verbose_name='关联ip字段'),
        ),
    ]
