# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0006_addressconfig_divice_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressconfig',
            name='divices',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divices.divices', to_field='divice_ip', verbose_name='关联站点'),
        ),
    ]
