# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-06 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createdata', '0007_auto_20190805_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressconfig',
            name='divices',
        ),
    ]
