# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-12-25 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=50)),
                ('EquipTemplateType', models.CharField(max_length=50)),
                ('LibName', models.CharField(max_length=50)),
                ('CommandId', models.CharField(max_length=50)),
                ('CommandName', models.CharField(max_length=150)),
                ('CommandToken', models.CharField(max_length=50)),
                ('ParameterId', models.CharField(max_length=50)),
                ('ParameterName', models.CharField(max_length=50)),
                ('ParameterValue', models.CharField(max_length=50)),
                ('Meaning', models.CharField(max_length=50)),
                ('Commands_ip', models.CharField(max_length=50)),
                ('Commands_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '控制信息表',
                'verbose_name_plural': '控制信息表',
                'db_table': 'tb_Commands',
            },
        ),
        migrations.CreateModel(
            name='equipments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipId', models.CharField(max_length=50)),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipmentName', models.CharField(max_length=50)),
                ('PortId', models.CharField(max_length=25, null=True)),
                ('EquipAddress', models.CharField(max_length=25)),
                ('LibName', models.CharField(max_length=50)),
                ('Equipment_ip', models.CharField(max_length=50)),
                ('Equipment_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '设备中间表',
                'verbose_name_plural': '设备中间表',
                'db_table': 'tb_equipments',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=50)),
                ('EventId', models.CharField(max_length=50)),
                ('EventName', models.CharField(max_length=150)),
                ('ConditionId', models.CharField(default='null', max_length=50, null=True)),
                ('Meaning', models.CharField(default='null', max_length=150, null=True)),
                ('EventSeverity', models.CharField(default='null', max_length=50, null=True)),
                ('StartCompareValue', models.CharField(default='null', max_length=50, null=True)),
                ('StartOperation', models.CharField(default='null', max_length=50, null=True)),
                ('Events_ip', models.CharField(max_length=50)),
                ('Events_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '告警信息表',
                'verbose_name_plural': '告警信息表',
                'db_table': 'tb_Events',
            },
        ),
        migrations.CreateModel(
            name='logactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogActionId', models.CharField(max_length=50)),
                ('ActionName', models.CharField(max_length=50)),
                ('TriggerType', models.CharField(max_length=50)),
                ('ActionId', models.CharField(max_length=25)),
                ('EquipmentId', models.CharField(max_length=25)),
                ('ActionValue', models.CharField(max_length=50)),
                ('logactions_ip', models.CharField(max_length=50)),
                ('logactions_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '设备第三张表<LogActions>',
                'verbose_name_plural': '设备第三张表<LogActions>',
                'db_table': 'tb_logactions',
            },
        ),
        migrations.CreateModel(
            name='port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PortId', models.CharField(max_length=50)),
                ('PortNo', models.CharField(max_length=50)),
                ('PortType', models.CharField(max_length=50)),
                ('PortSetting', models.CharField(max_length=50)),
                ('PortLibName', models.CharField(blank=True, max_length=50, null=True)),
                ('Description', models.CharField(blank=True, max_length=50, null=True)),
                ('port_ip', models.CharField(max_length=50)),
                ('port_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '端口信息表',
                'verbose_name_plural': '端口信息表',
                'db_table': 'tb_port',
            },
        ),
        migrations.CreateModel(
            name='Signals_meaing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=150)),
                ('SignalId', models.CharField(max_length=10)),
                ('SignalName', models.CharField(max_length=150)),
                ('Unit', models.CharField(default='-', max_length=25)),
                ('StateValue', models.CharField(default='null', max_length=10, null=True)),
                ('Meaning', models.CharField(default='null', max_length=150, null=True)),
                ('Signals_ip', models.CharField(max_length=50)),
                ('Signals_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '状态信息meaing表',
                'verbose_name_plural': '状态信息meaing表',
                'db_table': 'tb_Signals_meaing',
            },
        ),
        migrations.CreateModel(
            name='XmlData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipid', models.CharField(max_length=20, verbose_name='设备ID')),
                ('sigid', models.CharField(max_length=20, verbose_name='信号ID')),
                ('reg_addr', models.CharField(max_length=20, verbose_name='寄存器地址')),
                ('name', models.CharField(max_length=150, verbose_name='信号名称')),
                ('float_data', models.FloatField(verbose_name='获取数据')),
                ('data_time', models.CharField(max_length=50, verbose_name='时间戳')),
                ('divice_ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
            options={
                'verbose_name': '实时信息表',
                'verbose_name_plural': '实时信息表',
                'db_table': 'tb_xmldata',
            },
        ),
    ]
