# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-28 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='EquipId',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='port',
            name='PortId',
            field=models.CharField(max_length=50),
        ),
    ]
