# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signals',
        ),
        migrations.RemoveField(
            model_name='signals_meaing',
            name='EquipTemplateType',
        ),
        migrations.RemoveField(
            model_name='signals_meaing',
            name='Expression',
        ),
        migrations.RemoveField(
            model_name='signals_meaing',
            name='LibName',
        ),
        migrations.RemoveField(
            model_name='signals_meaing',
            name='SignalBaseId',
        ),
        migrations.RemoveField(
            model_name='signals_meaing',
            name='SignalType',
        ),
        migrations.AlterField(
            model_name='signals_meaing',
            name='EquipTemplateName',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='signals_meaing',
            name='Meaning',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='signals_meaing',
            name='SignalId',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='signals_meaing',
            name='StateValue',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
