# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=50)),
                ('EquipTemplateType', models.CharField(max_length=50)),
                ('LibName', models.CharField(max_length=50)),
                ('CommandId', models.CharField(max_length=50)),
                ('CommandName', models.CharField(max_length=150)),
                ('CommandToken', models.CharField(max_length=50)),
                ('ParameterId', models.CharField(max_length=50)),
                ('ParameterName', models.CharField(max_length=50)),
                ('ParameterValue', models.CharField(max_length=50)),
                ('Meaning', models.CharField(max_length=50)),
                ('Signals_ip', models.CharField(max_length=50)),
                ('Signals_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '控制信息表',
                'verbose_name_plural': '控制信息表',
                'db_table': 'tb_Commands',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=50)),
                ('EquipTemplateType', models.CharField(max_length=50)),
                ('LibName', models.CharField(max_length=50)),
                ('EventId', models.CharField(max_length=50)),
                ('EventName', models.CharField(max_length=150)),
                ('ConditionId', models.CharField(max_length=50)),
                ('Meaning', models.CharField(max_length=50)),
                ('EventSeverity', models.CharField(max_length=50)),
                ('Signals_ip', models.CharField(max_length=50)),
                ('Signals_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '告警信息表',
                'verbose_name_plural': '告警信息表',
                'db_table': 'tb_Events',
            },
        ),
        migrations.CreateModel(
            name='logactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogActionId', models.CharField(max_length=50)),
                ('ActionName', models.CharField(max_length=50)),
                ('TriggerType', models.CharField(max_length=50)),
                ('ActionId', models.CharField(max_length=25)),
                ('EquipmentId', models.CharField(max_length=25)),
                ('ActionValue', models.CharField(max_length=50)),
                ('logactions_ip', models.CharField(max_length=50)),
                ('logactions_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '设备第三张表<LogActions>',
                'verbose_name_plural': '设备第三张表<LogActions>',
                'db_table': 'tb_logactions',
            },
        ),
        migrations.CreateModel(
            name='Signals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EquipTemplateId', models.CharField(max_length=50)),
                ('EquipTemplateName', models.CharField(max_length=50)),
                ('EquipTemplateType', models.CharField(max_length=50)),
                ('LibName', models.CharField(max_length=50)),
                ('SignalId', models.CharField(max_length=50)),
                ('SignalName', models.CharField(max_length=150)),
                ('SignalBaseId', models.CharField(max_length=150)),
                ('SignalType', models.CharField(max_length=150)),
                ('StateValue', models.CharField(blank=True, max_length=50, null=True)),
                ('Meaning', models.CharField(blank=True, max_length=50, null=True)),
                ('Signals_ip', models.CharField(max_length=50)),
                ('Signals_time', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': '状态信息表',
                'verbose_name_plural': '状态信息表',
                'db_table': 'tb_Signals',
            },
        ),
        migrations.DeleteModel(
            name='equiptemplate',
        ),
        migrations.AddField(
            model_name='equipments',
            name='PortId',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='EquipAddress',
            field=models.CharField(max_length=25),
        ),
    ]
