# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0002_auto_20191128_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signals_meaing',
            name='Unit',
            field=models.CharField(default='-', max_length=25),
        ),
    ]
