# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-17 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0002_auto_20191017_1229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commands',
            old_name='Signals_ip',
            new_name='Commands_ip',
        ),
        migrations.RenameField(
            model_name='commands',
            old_name='Signals_time',
            new_name='Commands_time',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Signals_ip',
            new_name='Events_ip',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='Signals_time',
            new_name='Events_time',
        ),
    ]
