# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-28 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmldata', '0003_auto_20191128_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='EquipTemplateType',
        ),
        migrations.RemoveField(
            model_name='events',
            name='LibName',
        ),
        migrations.AlterField(
            model_name='events',
            name='ConditionId',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='EventSeverity',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='Meaning',
            field=models.CharField(default='null', max_length=150),
        ),
        migrations.AlterField(
            model_name='events',
            name='StartCompareValue',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='events',
            name='StartOperation',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
